### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [Maxetto/AntiJoinBot#7]
logs
```
[00:38:17] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to AntiJoinBot v5.0
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1090]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1090]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1090]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1090]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1090]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:352) [patched_1.11.2.jar:git-Paper-1090]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:178) [patched_1.11.2.jar:git-Paper-1090]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:121) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:115) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:74) [ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.F_(SpigotLoginListenerPlay.java:67) [ProtocolSupport.jar:?]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:239) [patched_1.11.2.jar:git-Paper-1090]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.11.2.jar:git-Paper-1090]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925) [patched_1.11.2.jar:git-Paper-1090]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1090]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1090]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1090]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 32,412,055 milliseconds ago.  The last packet sent successfully to the server was 32,412,056 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at sun.reflect.GeneratedConstructorAccessor285.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3743) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2506) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.certox.MySQL.setUserName(MySQL.java:171) ~[?:?]
	at com.certox.Core.onPlayerJoinEvent(Core.java:240) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor537.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1090]
	... 17 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_121]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:1.8.0_121]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[?:1.8.0_121]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_121]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_121]
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3725) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2506) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739) ~[patched_1.11.2.jar:git-Paper-1090]
	at com.certox.MySQL.setUserName(MySQL.java:171) ~[?:?]
	at com.certox.Core.onPlayerJoinEvent(Core.java:240) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor537.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1090]
	... 17 more
```

timings 
https://timings.aikar.co/?id=31dbf7be1bb24afdbfa97c27633db9a3

**Comment by Maxetto** [comment]
You need to increase the "wait_timeout" in your MySQL Configuration.

We are already trying to reconnect to it, plugin-wise.


If this doesn't solve your issue already, then you have something in your machine that is killing connections (Firewall?) as stated here:
`Caused by: java.net.SocketException: Broken pipe (Write failed)`

**Comment by ghost** [comment]
ok. i fixed, thx :3
